### ISSUE TITLE
Mining Status card on homepage: Copy 

### ISSUE THREAD

**Issue by jzaluski** [aionnetwork/aion_explorer#1]
![screen shot 2018-03-03 at 3 25 57 pm](https://user-images.githubusercontent.com/5472416/36939105-a2383dae-1ef9-11e8-8ec9-c514188ec1d5.png)

1. "MINING | EQUI2109"  instead of EQUIHASH
2. Sol/s instead of H/s

**Comment by ali-sharif** [comment]
1. Fixed in UI. Will be pushed with next UI build.

2. Sol/s seems to be interchangable with H/s for equihash-based PoW chains and seems to be calculated the same way from a first glance (last block's difficulty / avg block time over last N blocks). Need to do more research on vocabulary used by miners of other PoW-Equihash-type chains before making the change.

**Comment by jzaluski** [comment]
Typeo - difficulty.
![image](https://user-images.githubusercontent.com/5472416/37115396-05068b80-2219-11e8-89e2-b17a339ecba6.png)

**Comment by ali-sharif** [comment]
done.
